DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS urls;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE urls (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    shortened_url TEXT UNIQUE NOT NULL,
    full_url TEXT NOT NULL
);

INSERT INTO urls (shortened_url, full_url) VALUES ("aBcD", "https://example.com/");